# Generated by Django 2.1.2 on 2018-10-15 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('datetime_reached', models.DateTimeField(auto_now_add=True)),
                ('game_played', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dprev_backend.Game')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoNamePair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_link', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('game_with_photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dprev_backend.Game')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='gameresult',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dprev_backend.User'),
        ),
        migrations.AddField(
            model_name='game',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dprev_backend.User'),
        ),
    ]
