# Generated by Django 2.1.2 on 2018-10-16 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dprev_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photonamequestion',
            name='correct',
            field=models.BooleanField(default=True),
        ),
    ]
