# Generated by Django 2.1.2 on 2018-10-16 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dprev_backend', '0002_auto_20181016_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_made', to='dprev_backend.DPrevUser'),
        ),
        migrations.AlterField(
            model_name='gameresult',
            name='game_played',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_result_history', to='dprev_backend.Game'),
        ),
        migrations.AlterField(
            model_name='gameresult',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_result_history', to='dprev_backend.DPrevUser'),
        ),
        migrations.AlterField(
            model_name='photonamepair',
            name='game_with_photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_name_pairs', to='dprev_backend.Game'),
        ),
    ]
