# Generated by Django 2.1.2 on 2018-10-16 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dprev_backend', '0003_auto_20181016_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='dprevuser',
            name='password',
            field=models.CharField(default='null', max_length=50),
            preserve_default=False,
        ),
    ]
