# Generated by Django 2.1.2 on 2018-10-16 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dprev_backend', '0004_dprevuser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='dprevuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
